language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
  - "iojs-v1.1.0"
branches:
  only:
    - master
    - v1.0.0
    - v2.0.0
    - v3.0.0
script:
  - "npm run-script cover"
  - "npm run-script lint"
